DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS contas;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    conclusao TEXT NOT NULL,
    departamentos TEXT NOT NULL,
    status TEXT NOT NULL,
    anexos TEXT NOT NULL
);

CREATE TABLE contas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email TEXT NOT NULL,
    senha TEXT NOT NULL
);